// <auto-generated />
namespace PeugeotWorkFlow.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class notif : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(notif));
        
        string IMigrationMetadata.Id
        {
            get { return "201703262234510_notif"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
